#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
STARTUP_DIR="${IPYTHONDIR:-$HOME/.ipython}/profile_default/startup"
STARTUP_FILE="$STARTUP_DIR/10-polarcap-startup.py"

mkdir -p "$STARTUP_DIR"

cat > "$STARTUP_FILE" <<EOF
# Auto-generated by polarcap_analysis/scripts/ipython_startup/install.sh
from __future__ import annotations

import builtins
import os
import sys
from pathlib import Path

REPO_ROOT = Path(os.environ.get("POLARCAP_REPO_ROOT", r"$REPO_ROOT")).expanduser().resolve()
SRC_DIR = REPO_ROOT / "src"
if SRC_DIR.is_dir() and str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

try:
    from polarcap_runtime import import_local_utilities, is_server, setup_notebook_path

    setup_notebook_path(REPO_ROOT)
    import_local_utilities(REPO_ROOT)
    builtins.is_server = is_server
except Exception as exc:
    builtins.is_server = lambda: False
    print(f"[polarcap-startup] warning: {exc}")
EOF

echo "Installed: $STARTUP_FILE"
echo "Restart Jupyter kernels to activate. is_server() is available globally."
