"""Helpers for compiling manuscript-facing CSV and LaTeX tables."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import pandas as pd
import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]

LATEX_ESCAPES = {
    "\\": r"\textbackslash{}",
    "&": r"\&",
    "%": r"\%",
    "$": r"\$",
    "#": r"\#",
    "_": r"\_",
    "{": r"\{",
    "}": r"\}",
    "~": r"\textasciitilde{}",
    "^": r"\textasciicircum{}",
}


def load_manifest(path: Path) -> dict[str, Any]:
    """Return paper-table manifest as a plain dict."""
    with path.open(encoding="utf-8") as handle:
        manifest = yaml.safe_load(handle) or {}
    if not isinstance(manifest, dict):
        raise TypeError(f"Expected dict manifest in {path}, got {type(manifest).__name__}")
    manifest.setdefault("tables", [])
    return manifest


def resolve_repo_path(path_like: str | Path) -> Path:
    """Resolve repo-relative paths while preserving absolute paths."""
    path = Path(path_like)
    return path if path.is_absolute() else REPO_ROOT / path


def ensure_parent(path: Path) -> None:
    """Create parent directory for a target path."""
    path.parent.mkdir(parents=True, exist_ok=True)


def latex_escape(value: Any) -> str:
    """Escape plain-text values for safe use in LaTeX tabular cells."""
    text = str(value)
    for src, repl in LATEX_ESCAPES.items():
        text = text.replace(src, repl)
    return text


def _format_numeric(value: float, fmt: str) -> str:
    if fmt == "int":
        return f"{int(round(value))}"
    if fmt.startswith("float"):
        digits = int(fmt.replace("float", "") or "2")
        return f"{value:.{digits}f}"
    if fmt.startswith("sci"):
        digits = int(fmt.replace("sci", "") or "1")
        return f"{value:.{digits}e}"
    if fmt.startswith("percent"):
        digits = int(fmt.replace("percent", "") or "1")
        return f"{100.0 * value:.{digits}f}"
    return f"{value}"


def format_cell(value: Any, fmt: str | None = None) -> str:
    """Format one display cell according to a simple manifest format key."""
    if value is None or (isinstance(value, float) and pd.isna(value)) or pd.isna(value):
        return ""

    fmt = fmt or "str"
    if fmt == "bool":
        mapping = {"TRUE": "Yes", "FALSE": "No", "YES": "Yes", "NO": "No"}
        return mapping.get(str(value).strip().upper(), latex_escape(value))
    if fmt == "station":
        try:
            return f"S{int(value) + 1}"
        except Exception:
            return latex_escape(value)
    if fmt == "raw":
        return str(value)
    if fmt in {"int"} or fmt.startswith(("float", "sci", "percent")):
        try:
            return _format_numeric(float(value), fmt)
        except Exception:
            return latex_escape(value)
    return latex_escape(value)


def render_table_environment(
    df: pd.DataFrame,
    spec: dict[str, Any],
    source_csvs: list[str],
    *,
    generator: str | None = None,
) -> str:
    """Render one full LaTeX table environment from a DataFrame and manifest spec."""
    columns = spec["display_columns"]
    env = spec.get("tex_environment", "table")
    position = spec.get("tex_position", "ht")
    use_resize = bool(spec.get("tex_resize_to_textwidth", False))
    align = spec.get("tex_align") or ("l" * len(columns))
    caption = spec["caption"]
    label = spec["latex_label"]

    header = " & ".join(latex_escape(col.get("label", col["name"])) for col in columns)
    body_lines: list[str] = []
    for record in df.to_dict(orient="records"):
        cells = [format_cell(record.get(col["name"]), col.get("fmt")) for col in columns]
        body_lines.append(" & ".join(cells) + r" \\")

    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    gen_line = (
        f"% Generated by {generator}"
        if generator
        else "% Generated by scripts/analysis/synthesis/run_paper_tables.py"
    )
    lines = [
        gen_line,
        f"% Generated at: {generated_at}",
        "% Source CSVs:",
    ]
    lines.extend(f"%   - {src}" for src in source_csvs)
    lines.extend(
        [
            rf"\begin{{{env}}}[{position}]",
            r"\centering",
            rf"\caption{{{caption}}}",
            rf"\label{{{label}}}",
        ]
    )
    if use_resize:
        lines.append(r"\resizebox{\textwidth}{!}{%")
    lines.extend(
        [
            rf"\begin{{tabular}}{{{align}}}",
            r"\hline",
            header + r" \\",
            r"\hline",
        ]
    )
    lines.extend(body_lines or [r"\multicolumn{1}{l}{No rows available.} \\"])
    lines.extend([r"\hline", r"\end{tabular}"])
    if use_resize:
        lines.append("}")
    lines.append(rf"\end{{{env}}}")
    lines.append("")
    return "\n".join(lines)


def copy_if_changed(src: Path, dst: Path) -> None:
    """Copy rendered content to destination while avoiding needless rewrites."""
    ensure_parent(dst)
    content = src.read_text(encoding="utf-8")
    if dst.exists() and dst.read_text(encoding="utf-8") == content:
        return
    dst.write_text(content, encoding="utf-8")


def add_provenance(
    df: pd.DataFrame,
    *,
    table_id: str,
    source_csvs: list[str],
    selection_rule: str,
) -> pd.DataFrame:
    """Append common provenance columns to a compiled CSV."""
    out = df.copy()
    out["table_id"] = table_id
    out["selection_rule"] = selection_rule
    out["source_csvs"] = ";".join(source_csvs)
    return out
