const REGIONS = [
  {
    id: "home-valley",
    name: "Home Valley",
    blurb: "Lock in ASDF · JKL; without thinking",
  },
  {
    id: "thumb-shores",
    name: "Thumb Shores",
    blurb: "Space & Backspace with thumbs, not fingers",
  },
  {
    id: "enter-cave",
    name: "Enter Cave",
    blurb: "Right thumb owns Enter — never pinky reach",
  },
  {
    id: "shift-highlands",
    name: "Shift Highlands",
    blurb: "Thumb Shift for capitals & symbols",
  },
  {
    id: "mac-ghost",
    name: "MacBook Ghost",
    blurb: "Unlearn MacBook habits on the contoured layout",
  },
  {
    id: "speed-plains",
    name: "Speed Plains",
    blurb: "Real sentences — prove the Kinesis is faster",
  },
];

const LESSONS = [
  {
    id: "home-1",
    region: "home-valley",
    title: "Feel the wells",
    desc: "Let fingers fall into the home row. No rush — accuracy builds speed later.",
    focus: "Home row",
    text: "asdf jkl; asdf jkl; fjdk sl;a fjdk sl;a",
    goals: { accuracy: 92, wpm: 12 },
  },
  {
    id: "home-2",
    region: "home-valley",
    title: "Alternating hands",
    desc: "Each keystroke alternates left/right. This is how you'll regain flow.",
    focus: "Alternation",
    text: "fad jad fad jad; lad kad lad kad; ask lad; ask lad;",
    goals: { accuracy: 93, wpm: 14 },
  },
  {
    id: "home-3",
    region: "home-valley",
    title: "Home row words",
    desc: "Short real words anchored on the home row.",
    focus: "Words",
    text: "fall salad flask ask lad dash fall salad flask ask lad dash",
    goals: { accuracy: 94, wpm: 16 },
  },
  {
    id: "thumb-1",
    region: "thumb-shores",
    title: "Right thumb space",
    desc: "On Advantage 360, Space lives under your right thumb. Tap it — don't reach with your right index.",
    focus: "Right thumb · Space",
    text: "a a a a a   a a a a a   fad fad fad   salad salad",
    goals: { accuracy: 94, wpm: 14 },
    thumbKeys: [" "],
  },
  {
    id: "thumb-2",
    region: "thumb-shores",
    title: "Left thumb backspace",
    desc: "Backspace is a thumb key. Light tap — slide your hand slightly if needed, don't stretch.",
    focus: "Left thumb · Backspace",
    text: "asdf asdf asdf jkl; jkl; jkl;",
    goals: { accuracy: 90, wpm: 12 },
    thumbKeys: ["Backspace"],
    practiceBackspace: true,
  },
  {
    id: "thumb-3",
    region: "thumb-shores",
    title: "Thumb rhythm",
    desc: "Space between every word. Build the thumb-finger dance.",
    focus: "Thumb rhythm",
    text: "the quick thumb wins the race the quick thumb wins the race",
    goals: { accuracy: 93, wpm: 18 },
    thumbKeys: [" "],
  },
  {
    id: "enter-1",
    region: "enter-cave",
    title: "Enter with right thumb",
    desc: "MacBook trained you to reach Enter with pinky. Here, right thumb only. Press Enter at each | marker.",
    focus: "Right thumb · Enter",
    text: "line one|line two|line three|line four|",
    goals: { accuracy: 90, wpm: 10 },
    thumbKeys: ["Enter"],
    enterMarkers: true,
  },
  {
    id: "enter-2",
    region: "enter-cave",
    title: "Paragraph breaks",
    desc: "Thumb Enter after every sentence. Keep right hand relaxed.",
    focus: "Enter flow",
    text: "Type with thumbs.|Short lines build habit.|Enter is near your palm.|",
    goals: { accuracy: 91, wpm: 12 },
    thumbKeys: ["Enter"],
    enterMarkers: true,
  },
  {
    id: "shift-1",
    region: "shift-highlands",
    title: "Thumb shift capitals",
    desc: "Hold right thumb Shift, strike letter with finger, release. No left-pinky stretch.",
    focus: "Right thumb · Shift",
    text: "Aa Bb Cc Dd Ee Ff Gg Hh Ii Jj Kk Ll",
    goals: { accuracy: 88, wpm: 10 },
    thumbKeys: ["Shift"],
    needsShift: true,
  },
  {
    id: "shift-2",
    region: "shift-highlands",
    title: "Capitalized words",
    desc: "Names and starts of sentences — all via thumb Shift.",
    focus: "Shift + flow",
    text: "Kinesis World trains thumbs. Advantage Three Sixty feels strange then fast.",
    goals: { accuracy: 90, wpm: 14 },
    thumbKeys: ["Shift"],
    needsShift: true,
  },
  {
    id: "mac-1",
    region: "mac-ghost",
    title: "Unlearn Command reach",
    desc: "On Mac layout, Command sits on left thumb cluster. Practice word + imagined shortcut rhythm.",
    focus: "Left thumb · ⌘",
    text: "save copy paste undo save copy paste undo tab switch tab switch",
    goals: { accuracy: 92, wpm: 16 },
    thumbKeys: ["Meta"],
    mentalNote: "When you need ⌘, left thumb — not curled left pinky.",
  },
  {
    id: "mac-2",
    region: "mac-ghost",
    title: "Punctuation without stretch",
    desc: "Reach punctuation from home row; use thumbs for Space and Enter between clauses.",
    focus: "Right hand neutral",
    text: "hello, world; hello, world; yes — thumbs; yes — thumbs;",
    goals: { accuracy: 91, wpm: 15 },
    thumbKeys: [" ", "Enter"],
    avoidRightPinky: ["Enter", "'", '"'],
  },
  {
    id: "speed-1",
    region: "speed-plains",
    title: "Thumb-powered sentence",
    desc: "One calm paragraph. Thumbs for Space, Enter, Shift when needed.",
    focus: "Full stack",
    text: "The Advantage 360 rewards patience. Your right thumb handles Space and Enter while fingers stay in the wells. Daily practice here beats forcing speed on real work.",
    goals: { accuracy: 93, wpm: 20 },
    thumbKeys: [" ", "Enter", "Shift"],
  },
  {
    id: "speed-2",
    region: "speed-plains",
    title: "Beat your MacBook ghost",
    desc: "Longer flow text. Goal: smooth accuracy first — speed follows in week two.",
    focus: "Speed quest",
    text: "Muscle memory is built in minutes per day not hours per night. Thumb keys remove awkward right hand angles. Soon this keyboard will feel faster than the MacBook because your hands barely move.",
    goals: { accuracy: 94, wpm: 24 },
    thumbKeys: [" ", "Enter", "Shift", "Backspace"],
  },
  {
    id: "speed-3",
    region: "speed-plains",
    title: "Kinesis master run",
    desc: "Final quest. Prove the layout works for you.",
    focus: "Mastery",
    text: "I type with thumbs and home row. My right hand stays healthy. The contoured wells guide my fingers. Kinesis World made the switch gentle. Now I write faster with less strain.",
    goals: { accuracy: 95, wpm: 28 },
    thumbKeys: [" ", "Enter", "Shift", "Backspace"],
  },
];

const DAILY_DRILL_IDS = [
  "thumb-1",
  "enter-1",
  "shift-1",
  "home-3",
  "speed-1",
];

if (typeof window !== "undefined") {
  window.KINESIS_LESSONS = { REGIONS, LESSONS, DAILY_DRILL_IDS };
}
