const REGIONS = [
  {
    id: "home-valley",
    name: "Home Valley",
    blurb: "Lock in ASDF · JKL; without thinking",
  },
  {
    id: "thumb-shores",
    name: "Thumb Shores",
    blurb: "Space & Backspace with thumbs, not fingers",
  },
  {
    id: "enter-cave",
    name: "Enter Cave",
    blurb: "Right thumb owns Enter — never pinky reach",
  },
  {
    id: "shift-highlands",
    name: "Shift Highlands",
    blurb: "Thumb Shift for capitals & symbols",
  },
  {
    id: "mac-ghost",
    name: "MacBook Ghost",
    blurb: "Unlearn MacBook habits on the contoured layout",
  },
  {
    id: "speed-plains",
    name: "Speed Plains",
    blurb: "Real sentences — prove the Kinesis is faster",
  },
  {
    id: "code-glyphs",
    name: "Code Glyphs",
    blurb: "Brackets, operators, pipes — the symbols devs live in",
  },
  {
    id: "python-grove",
    name: "Python Grove",
    blurb: "def, import, indentation — thumb Enter after colons",
  },
  {
    id: "bash-dock",
    name: "Bash Dock",
    blurb: "Shell paths, pipes, redirects, flags",
  },
  {
    id: "markdown-forge",
    name: "Markdown Forge",
    blurb: "Headers, links, fences — docs and READMEs",
  },
  {
    id: "fortran-lab",
    name: "Fortran Lab",
    blurb: "program, implicit none, do loops — scientific syntax",
  },
  {
    id: "vim-tmux-dojo",
    name: "Vim & Tmux Dojo",
    blurb: "Ex commands, Neovim config, tmux splits",
  },
];

const LESSONS = [
  {
    id: "home-1",
    region: "home-valley",
    title: "Feel the wells",
    desc: "Let fingers fall into the home row. No rush — accuracy builds speed later.",
    focus: "Home row",
    text: "asdf jkl; asdf jkl; fjdk sl;a fjdk sl;a",
    goals: { accuracy: 92, wpm: 12 },
  },
  {
    id: "home-2",
    region: "home-valley",
    title: "Alternating hands",
    desc: "Each keystroke alternates left/right. This is how you'll regain flow.",
    focus: "Alternation",
    text: "fad jad fad jad; lad kad lad kad; ask lad; ask lad;",
    goals: { accuracy: 93, wpm: 14 },
  },
  {
    id: "home-3",
    region: "home-valley",
    title: "Home row words",
    desc: "Short real words anchored on the home row.",
    focus: "Words",
    text: "fall salad flask ask lad dash fall salad flask ask lad dash",
    goals: { accuracy: 94, wpm: 16 },
  },
  {
    id: "thumb-1",
    region: "thumb-shores",
    title: "Right thumb space",
    desc: "On Advantage 360, Space lives under your right thumb. Tap it — don't reach with your right index.",
    focus: "Right thumb · Space",
    text: "a a a a a   a a a a a   fad fad fad   salad salad",
    goals: { accuracy: 94, wpm: 14 },
    thumbKeys: [" "],
  },
  {
    id: "thumb-2",
    region: "thumb-shores",
    title: "Left thumb backspace",
    desc: "Backspace is a thumb key. Light tap — slide your hand slightly if needed, don't stretch.",
    focus: "Left thumb · Backspace",
    text: "asdf asdf asdf jkl; jkl; jkl;",
    goals: { accuracy: 90, wpm: 12 },
    thumbKeys: ["Backspace"],
    practiceBackspace: true,
  },
  {
    id: "thumb-3",
    region: "thumb-shores",
    title: "Thumb rhythm",
    desc: "Space between every word. Build the thumb-finger dance.",
    focus: "Thumb rhythm",
    text: "the quick thumb wins the race the quick thumb wins the race",
    goals: { accuracy: 93, wpm: 18 },
    thumbKeys: [" "],
  },
  {
    id: "enter-1",
    region: "enter-cave",
    title: "Enter with right thumb",
    desc: "MacBook trained you to reach Enter with pinky. Here, right thumb only. Press Enter at each line break.",
    focus: "Right thumb · Enter",
    text: "line one⏎line two⏎line three⏎line four⏎",
    goals: { accuracy: 90, wpm: 10 },
    thumbKeys: ["Enter"],
    enterMarkers: true,
  },
  {
    id: "enter-2",
    region: "enter-cave",
    title: "Paragraph breaks",
    desc: "Thumb Enter after every sentence. Keep right hand relaxed.",
    focus: "Enter flow",
    text: "Type with thumbs.⏎Short lines build habit.⏎Enter is near your palm.⏎",
    goals: { accuracy: 91, wpm: 12 },
    thumbKeys: ["Enter"],
    enterMarkers: true,
  },
  {
    id: "shift-1",
    region: "shift-highlands",
    title: "Thumb shift capitals",
    desc: "Hold right thumb Shift, strike letter with finger, release. No left-pinky stretch.",
    focus: "Right thumb · Shift",
    text: "Aa Bb Cc Dd Ee Ff Gg Hh Ii Jj Kk Ll",
    goals: { accuracy: 88, wpm: 10 },
    thumbKeys: ["Shift"],
    needsShift: true,
  },
  {
    id: "shift-2",
    region: "shift-highlands",
    title: "Capitalized words",
    desc: "Names and starts of sentences — all via thumb Shift.",
    focus: "Shift + flow",
    text: "Kinesis World trains thumbs. Advantage Three Sixty feels strange then fast.",
    goals: { accuracy: 90, wpm: 14 },
    thumbKeys: ["Shift"],
    needsShift: true,
  },
  {
    id: "mac-1",
    region: "mac-ghost",
    title: "Unlearn Command reach",
    desc: "On Mac layout, Command sits on left thumb cluster. Practice word + imagined shortcut rhythm.",
    focus: "Left thumb · ⌘",
    text: "save copy paste undo save copy paste undo tab switch tab switch",
    goals: { accuracy: 92, wpm: 16 },
    thumbKeys: ["Meta"],
    mentalNote: "When you need ⌘, left thumb — not curled left pinky.",
  },
  {
    id: "mac-2",
    region: "mac-ghost",
    title: "Punctuation without stretch",
    desc: "Reach punctuation from home row; use thumbs for Space and Enter between clauses.",
    focus: "Right hand neutral",
    text: "hello, world; hello, world; yes — thumbs; yes — thumbs;",
    goals: { accuracy: 91, wpm: 15 },
    thumbKeys: [" ", "Enter"],
    avoidRightPinky: ["Enter", "'", '"'],
  },
  {
    id: "speed-1",
    region: "speed-plains",
    title: "Thumb-powered sentence",
    desc: "One calm paragraph. Thumbs for Space, Enter, Shift when needed.",
    focus: "Full stack",
    text: "The Advantage 360 rewards patience. Your right thumb handles Space and Enter while fingers stay in the wells. Daily practice here beats forcing speed on real work.",
    goals: { accuracy: 93, wpm: 20 },
    thumbKeys: [" ", "Enter", "Shift"],
  },
  {
    id: "speed-2",
    region: "speed-plains",
    title: "Beat your MacBook ghost",
    desc: "Longer flow text. Goal: smooth accuracy first — speed follows in week two.",
    focus: "Speed quest",
    text: "Muscle memory is built in minutes per day not hours per night. Thumb keys remove awkward right hand angles. Soon this keyboard will feel faster than the MacBook because your hands barely move.",
    goals: { accuracy: 94, wpm: 24 },
    thumbKeys: [" ", "Enter", "Shift", "Backspace"],
  },
  {
    id: "speed-3",
    region: "speed-plains",
    title: "Kinesis master run",
    desc: "Final quest. Prove the layout works for you.",
    focus: "Mastery",
    text: "I type with thumbs and home row. My right hand stays healthy. The contoured wells guide my fingers. Kinesis World made the switch gentle. Now I write faster with less strain.",
    goals: { accuracy: 95, wpm: 28 },
    thumbKeys: [" ", "Enter", "Shift", "Backspace"],
  },
  {
    id: "glyph-1",
    region: "code-glyphs",
    title: "Parens and brackets",
    desc: "Shift digits for ( ) [ ]. Left hand heavy — keep wrists straight.",
    focus: "() []",
    text: "(x) [i] (arr[0]) [key] (func(x, y))",
    goals: { accuracy: 90, wpm: 10 },
    code: true,
    requires: ["shift-2"],
  },
  {
    id: "glyph-2",
    region: "code-glyphs",
    title: "Braces and angles",
    desc: "Curly braces and comparison operators — common in Python, JS, shells.",
    focus: "{} <>",
    text: "{key: val} if x < n and y > 0: pass",
    goals: { accuracy: 89, wpm: 10 },
    code: true,
  },
  {
    id: "glyph-3",
    region: "code-glyphs",
    title: "Operators and equals",
    desc: "Assignment, arithmetic, and equality — thumb Shift for + and =.",
    focus: "= + - * /",
    text: "x = a + b - c * d / n  count += 1  x == y  x != 0",
    goals: { accuracy: 90, wpm: 12 },
    code: true,
  },
  {
    id: "glyph-4",
    region: "code-glyphs",
    title: "Pipes and redirects",
    desc: "Shell bread and butter. Pipe is Shift+\\ on US layout — practice the reach calmly.",
    focus: "| > >>",
    text: "cmd | grep foo > out.txt 2> err.log  cat a >> b",
    goals: { accuracy: 88, wpm: 9 },
    code: true,
  },
  {
    id: "glyph-5",
    region: "code-glyphs",
    title: "Quotes and hashes",
    desc: "Strings, comments, and doc markers across languages.",
    focus: "' \" #",
    text: "'single' \"double\"  # comment  \"\"\"doc\"\"\"  f\"{x}\"",
    goals: { accuracy: 89, wpm: 11 },
    code: true,
  },
  {
    id: "py-1",
    region: "python-grove",
    title: "def and colon",
    desc: "Function header then thumb Enter. Indent next line with Tab (right thumb on Kinesis).",
    focus: "def · indent",
    text: "def mean(xs):⏎→return sum(xs) / len(xs)",
    goals: { accuracy: 90, wpm: 8 },
    code: true,
    enterMarkers: true,
    tabMarkers: true,
    thumbKeys: ["Enter", "Tab"],
  },
  {
    id: "py-2",
    region: "python-grove",
    title: "import lines",
    desc: "Import statements — no semicolons, clean lines.",
    focus: "import",
    text: "import numpy as np⏎import xarray as xr⏎from pathlib import Path",
    goals: { accuracy: 92, wpm: 12 },
    code: true,
    enterMarkers: true,
    thumbKeys: ["Enter"],
  },
  {
    id: "py-3",
    region: "python-grove",
    title: "if and elif blocks",
    desc: "Colon + Enter + indent. Python shape you type all day.",
    focus: "blocks",
    text: "if x > 0:⏎→y = x⏎elif x < 0:⏎→y = -x⏎else:⏎→y = 0",
    goals: { accuracy: 89, wpm: 8 },
    code: true,
    enterMarkers: true,
    tabMarkers: true,
    thumbKeys: ["Enter", "Tab"],
  },
  {
    id: "py-4",
    region: "python-grove",
    title: "dicts and comprehensions",
    desc: "Brackets, colons, braces in one flow.",
    focus: "data structures",
    text: "cfg = {\"path\": \"/data\", \"n\": 10}⏎vals = [x * 2 for x in xs if x > 0]",
    goals: { accuracy: 88, wpm: 10 },
    code: true,
    enterMarkers: true,
    thumbKeys: ["Enter"],
  },
  {
    id: "py-5",
    region: "python-grove",
    title: "main guard",
    desc: "Standard script footer — muscle memory for project entry points.",
    focus: "__main__",
    text: "if __name__ == \"__main__\":⏎→main()",
    goals: { accuracy: 91, wpm: 10 },
    code: true,
    enterMarkers: true,
    tabMarkers: true,
    thumbKeys: ["Enter", "Tab"],
  },
  {
    id: "bash-1",
    region: "bash-dock",
    title: "Paths and variables",
    desc: "cd, $HOME, ${VAR} — terminal paths without looking.",
    focus: "paths",
    text: "cd ~/projects/data⏎echo $HOME⏎export PYTHONPATH=${PWD}/src",
    goals: { accuracy: 90, wpm: 11 },
    code: true,
    enterMarkers: true,
    thumbKeys: ["Enter"],
  },
  {
    id: "bash-2",
    region: "bash-dock",
    title: "Pipes and filters",
    desc: "Chain commands — pipe is the spine of the shell.",
    focus: "pipes",
    text: "ls -la | grep yaml⏎cat file.txt | sort | uniq -c⏎find . -name \"*.py\"",
    goals: { accuracy: 89, wpm: 10 },
    code: true,
    enterMarkers: true,
    thumbKeys: ["Enter"],
  },
  {
    id: "bash-3",
    region: "bash-dock",
    title: "Redirects and stderr",
    desc: "stdout/stderr redirection patterns you use in scripts and HPC jobs.",
    focus: "redirects",
    text: "python run.py > out.log 2>&1⏎tee run.log⏎cmd &> all.log",
    goals: { accuracy: 88, wpm: 9 },
    code: true,
    enterMarkers: true,
    thumbKeys: ["Enter"],
  },
  {
    id: "bash-4",
    region: "bash-dock",
    title: "Loops and tests",
    desc: "for, if, && — bash control flow.",
    focus: "control flow",
    text: "for f in *.nc; do⏎→ncdump -h \"$f\"⏎done⏎if [ -f cfg.yaml ]; then⏎→python run.py⏎fi",
    goals: { accuracy: 87, wpm: 8 },
    code: true,
    enterMarkers: true,
    tabMarkers: true,
    thumbKeys: ["Enter", "Tab"],
  },
  {
    id: "bash-5",
    region: "bash-dock",
    title: "Shebang and chmod",
    desc: "Executable scripts — first line and permissions.",
    focus: "scripts",
    text: "#!/usr/bin/env bash⏎set -euo pipefail⏎chmod +x scripts/run_chain.sh",
    goals: { accuracy: 90, wpm: 10 },
    code: true,
    enterMarkers: true,
    thumbKeys: ["Enter"],
  },
  {
    id: "md-1",
    region: "markdown-forge",
    title: "Headers and lists",
    desc: "README structure — hash headers, dash lists.",
    focus: "# lists",
    text: "# Project Title⏎## Setup⏎- install deps⏎- run tests",
    goals: { accuracy: 91, wpm: 11 },
    code: true,
    enterMarkers: true,
    thumbKeys: ["Enter"],
  },
  {
    id: "md-2",
    region: "markdown-forge",
    title: "Links and emphasis",
    desc: "Bracket-paren links and bold/italic markers.",
    focus: "links",
    text: "See [docs](https://example.com) for **bold** and *italic* notes.",
    goals: { accuracy: 90, wpm: 12 },
    code: true,
  },
  {
    id: "md-3",
    region: "markdown-forge",
    title: "Code fences",
    desc: "Triple backticks — Shift+` on US layout. Fence opening and closing.",
    focus: "```",
    text: "Use python blocks:⏎```python⏎print(\"hello\")⏎```",
    goals: { accuracy: 87, wpm: 8 },
    code: true,
    enterMarkers: true,
    thumbKeys: ["Enter", "Shift"],
  },
  {
    id: "md-4",
    region: "markdown-forge",
    title: "Tables and tasks",
    desc: "Pipe tables and GitHub task lists.",
    focus: "tables",
    text: "| col | val |⏎|-----|-----|⏎| a | 1 |⏎- [x] done⏎- [ ] todo",
    goals: { accuracy: 86, wpm: 9 },
    code: true,
    enterMarkers: true,
    thumbKeys: ["Enter"],
  },
  {
    id: "ftn-1",
    region: "fortran-lab",
    title: "program skeleton",
    desc: "Classic Fortran program wrapper — fixed vocabulary.",
    focus: "program",
    text: "program demo⏎implicit none⏎integer :: i, n⏎end program demo",
    goals: { accuracy: 90, wpm: 9 },
    code: true,
    enterMarkers: true,
    thumbKeys: ["Enter"],
  },
  {
    id: "ftn-2",
    region: "fortran-lab",
    title: "Types and arrays",
    desc: "real(8), allocatable, dimension — sci-code staples.",
    focus: "types",
    text: "real(8), allocatable :: field(:,:,:)⏎allocate(field(nx, ny, nz))",
    goals: { accuracy: 88, wpm: 9 },
    code: true,
    enterMarkers: true,
    thumbKeys: ["Enter"],
  },
  {
    id: "ftn-3",
    region: "fortran-lab",
    title: "do loops",
    desc: "Nested do/end do — thumb Enter between lines.",
    focus: "do loops",
    text: "do i = 1, n⏎→field(i) = 0.0d0⏎end do",
    goals: { accuracy: 89, wpm: 8 },
    code: true,
    enterMarkers: true,
    tabMarkers: true,
    thumbKeys: ["Enter", "Tab"],
  },
  {
    id: "ftn-4",
    region: "fortran-lab",
    title: "subroutine",
    desc: "Procedure boundaries — subroutine/end subroutine.",
    focus: "subroutine",
    text: "subroutine init(field, n)⏎→implicit none⏎→real(8), intent(inout) :: field(n)⏎end subroutine init",
    goals: { accuracy: 87, wpm: 7 },
    code: true,
    enterMarkers: true,
    tabMarkers: true,
    thumbKeys: ["Enter", "Tab"],
  },
  {
    id: "ftn-5",
    region: "fortran-lab",
    title: "use and modules",
    desc: "Modern Fortran module imports.",
    focus: "modules",
    text: "use iso_fortran_env, only: real64⏎use my_mod, only: init_field",
    goals: { accuracy: 90, wpm: 10 },
    code: true,
    enterMarkers: true,
    thumbKeys: ["Enter"],
  },
  {
    id: "vim-1",
    region: "vim-tmux-dojo",
    title: "Ex commands",
    desc: "Colon commands you type in Neovim — :w :q :split.",
    focus: ":ex",
    text: ":w⏎:q⏎:wq⏎:split⏎:terminal⏎:e config.lua",
    goals: { accuracy: 91, wpm: 10 },
    code: true,
    enterMarkers: true,
    thumbKeys: ["Enter", "Shift"],
  },
  {
    id: "vim-2",
    region: "vim-tmux-dojo",
    title: "Search and replace",
    desc: "/%s/ patterns — slashes and escapes.",
    focus: "search",
    text: "/error⏎:noh⏎:%s/foo/bar/g⏎:%s/old/new/gc",
    goals: { accuracy: 88, wpm: 9 },
    code: true,
    enterMarkers: true,
    thumbKeys: ["Enter", "Shift"],
  },
  {
    id: "vim-3",
    region: "vim-tmux-dojo",
    title: "Neovim lua config",
    desc: "init.lua snippets — keys, opts, lazy setup.",
    focus: "lua",
    text: "vim.keymap.set(\"n\", \"<leader>w\", \":w<CR>\")⏎require(\"lazy\").setup(\"plugins\")",
    goals: { accuracy: 86, wpm: 8 },
    code: true,
    enterMarkers: true,
    thumbKeys: ["Enter", "Shift"],
  },
  {
    id: "tmux-1",
    region: "vim-tmux-dojo",
    title: "tmux commands",
    desc: "Type tmux subcommands — alternative to memorizing prefix chords first.",
    focus: "tmux",
    text: "tmux new -s dev⏎tmux split-window -h⏎tmux attach -t dev⏎tmux list-sessions",
    goals: { accuracy: 90, wpm: 10 },
    code: true,
    enterMarkers: true,
    thumbKeys: ["Enter"],
  },
  {
    id: "tmux-2",
    region: "vim-tmux-dojo",
    title: "Dev workflow combo",
    desc: "Terminal + editor + tmux — a realistic short session.",
    focus: "workflow",
    text: "cd ~/proj && tmux new -s run⏎nvim src/main.py⏎:w⏎:split⏎:terminal⏎python -m pytest -q",
    goals: { accuracy: 85, wpm: 8 },
    code: true,
    enterMarkers: true,
    thumbKeys: ["Enter", "Shift", "Tab"],
  },
  {
    id: "dev-boss",
    region: "vim-tmux-dojo",
    title: "Dev boss run",
    desc: "Final programming quest — mixed Python, bash, markdown in one flow.",
    focus: "Mastery",
    text: "#!/usr/bin/env python3⏎def main():⏎→cfg = {\"n\": 10}⏎→print(f\"n={cfg['n']}\")⏎if __name__ == \"__main__\":⏎→main()",
    goals: { accuracy: 88, wpm: 10 },
    code: true,
    enterMarkers: true,
    tabMarkers: true,
    thumbKeys: ["Enter", "Tab", "Shift"],
  },
];

const DAILY_DRILL_IDS = [
  "thumb-1",
  "enter-1",
  "shift-1",
  "home-3",
  "speed-1",
];

const PROGRAMMING_DAILY_DRILL_IDS = [
  "glyph-3",
  "py-3",
  "bash-2",
  "vim-1",
  "dev-boss",
];

const PROGRAMMING_REGION_IDS = new Set([
  "code-glyphs",
  "python-grove",
  "bash-dock",
  "markdown-forge",
  "fortran-lab",
  "vim-tmux-dojo",
]);

if (typeof window !== "undefined") {
  window.KINESIS_LESSONS = {
    REGIONS,
    LESSONS,
    DAILY_DRILL_IDS,
    PROGRAMMING_DAILY_DRILL_IDS,
    PROGRAMMING_REGION_IDS,
  };
}
